set -euf -o pipefail

SOURCE_PASSWORD=${SOURCE_PASSWORD:-$RANDOM}
ADMIN_PASSWORD=${ADMIN_PASSWORD:-$RANDOM}
RELAY_PASSWORD=${RELAY_PASSWORD:-$RANDOM}
HOST=${HOST:-localhost}

# Scheduler settings
TIMEZONE=${TIMEZONE:-Europe/London}
SATURDAY_TIME=${SATURDAY_TIME:-18:00}
SUNDAY_TIME=${SUNDAY_TIME:-10:00}
SCHEDULE_USER=${SCHEDULE_USER:-admin}
SCHEDULE_PASSWORD_HASH=${SCHEDULE_PASSWORD_HASH:-}

[[ -f .env ]] && source .env